In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sents = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [7]:
vocabulary_size = 10000

In [8]:
sents

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [9]:
one_hot_repr = [one_hot(words,vocabulary_size) for words in sents]
one_hot_repr

[[8032, 552, 4934, 224],
 [8032, 552, 4934, 9957],
 [8032, 1445, 4934, 702],
 [2544, 2435, 5292, 238, 7116],
 [2544, 2435, 5292, 238, 9518],
 [507, 8032, 6417, 4934, 8400],
 [6082, 1681, 7202, 238]]

## Word Embeding

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences
import numpy as np

In [12]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,maxlen=sent_length,padding="pre")
print(embedded_docs)

[[   0    0    0    0 8032  552 4934  224]
 [   0    0    0    0 8032  552 4934 9957]
 [   0    0    0    0 8032 1445 4934  702]
 [   0    0    0 2544 2435 5292  238 7116]
 [   0    0    0 2544 2435 5292  238 9518]
 [   0    0    0  507 8032 6417 4934 8400]
 [   0    0    0    0 6082 1681 7202  238]]


In [13]:
dim = 10

In [15]:
model = Sequential()
model.add(Embedding(vocabulary_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step


array([[[ 0.00879798,  0.00513455,  0.04299123,  0.04209078,
          0.04320475,  0.04348807, -0.02147442,  0.04612279,
         -0.02071757,  0.03072933],
        [ 0.00879798,  0.00513455,  0.04299123,  0.04209078,
          0.04320475,  0.04348807, -0.02147442,  0.04612279,
         -0.02071757,  0.03072933],
        [ 0.00879798,  0.00513455,  0.04299123,  0.04209078,
          0.04320475,  0.04348807, -0.02147442,  0.04612279,
         -0.02071757,  0.03072933],
        [ 0.00879798,  0.00513455,  0.04299123,  0.04209078,
          0.04320475,  0.04348807, -0.02147442,  0.04612279,
         -0.02071757,  0.03072933],
        [-0.00720085,  0.02801124,  0.01348067, -0.02236072,
         -0.00601419, -0.01508586, -0.02691869,  0.00933437,
          0.03469796, -0.01047103],
        [ 0.03058703,  0.00637497,  0.02311348, -0.00046775,
          0.02484783,  0.043114  , -0.0165499 ,  0.02576849,
         -0.04856862, -0.01774666],
        [-0.018054  , -0.02554481, -0.00258737, -0.0

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 8032,  552, 4934,  224], dtype=int32)

In [20]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step


array([[[ 0.00879798,  0.00513455,  0.04299123,  0.04209078,
          0.04320475,  0.04348807, -0.02147442,  0.04612279,
         -0.02071757,  0.03072933],
        [ 0.00879798,  0.00513455,  0.04299123,  0.04209078,
          0.04320475,  0.04348807, -0.02147442,  0.04612279,
         -0.02071757,  0.03072933],
        [ 0.00879798,  0.00513455,  0.04299123,  0.04209078,
          0.04320475,  0.04348807, -0.02147442,  0.04612279,
         -0.02071757,  0.03072933],
        [ 0.00879798,  0.00513455,  0.04299123,  0.04209078,
          0.04320475,  0.04348807, -0.02147442,  0.04612279,
         -0.02071757,  0.03072933],
        [-0.00720085,  0.02801124,  0.01348067, -0.02236072,
         -0.00601419, -0.01508586, -0.02691869,  0.00933437,
          0.03469796, -0.01047103],
        [ 0.03058703,  0.00637497,  0.02311348, -0.00046775,
          0.02484783,  0.043114  , -0.0165499 ,  0.02576849,
         -0.04856862, -0.01774666],
        [-0.018054  , -0.02554481, -0.00258737, -0.0